plugins:
  postcss-import: {}
  postcss-cssnext: {}
  postcss-modules:
    generateScopedName: '[name]__[local]___[hash:base64:5]'
    modules: true
  autoprefixer:
    browsers:
      - last 2 versions
      - IE >= 10
      - iOS >= 9
